## The decision layer: the per-directive-turn loop that asks both commanders
## what their sides do next, and always has an answer.
##
## Forked from coworld-ctf's `src/ctf/decide.nim`, retargeted not rewritten.
##
## CADENCE: one directive turn every `directiveEvery` (10 turns) — 36 per seat
## per episode. At each turn the server builds BOTH seats' request bodies and
## issues them as ONE PARALLEL BATCH: lux-ai is a simultaneous-decision game,
## so querying seats one after another would double the wall clock for nothing.
##
## DEGRADE, NEVER HANG. Every wait here is bounded: attempt 1 gets
## `attempt1Ms`, the single retry gets `retryMs`, the whole turn is wrapped in a
## monotonic `turnBudgetMs` deadline, a rolling 60 s request counter caps the
## rate, and the budget guard switches the LLM off entirely rather than let the
## episode overrun. A provider throttle with no other candidate model skips the
## retry outright (it cannot land). On a second failure the seat plays the
## `forester` scripted directive — computed by THE SAME PROC the `forester`
## filler uses, imported and never duplicated, so the fallback and the filler
## cannot drift.

import std/[json, monotimes, os, strutils, times]

import curly

import directives, llm, sim

type
  SeatPolicy* = object
    ## What one seat registered as. A seat that registers with neither field —
    ## or never registers at all — is `forester`, the published default.
    isLlm*: bool
    prompt*: string
    baseline*: Baseline
    label*: string
    registered*: bool

  DecisionEngine* = object
    client*: LlmClient
    seats*: array[2, SeatPolicy]
    lastBatchStart*: MonoTime
    batchStarted*: bool
    llmOff*: bool
    requestTimes*: seq[MonoTime]   ## the rolling 60 s request counter.
    lastSnapshot*: array[2, array[3, int64]]
    lastCounts*: array[2, array[5, int]]

const
  RollingWindowSeconds = 60
  RollingRequestCap = 28
    ## `turnSpacingMs` pins the steady state at 20 req/min, but a turn in which
    ## both seats retry issues four requests. Above this trailing-60 s count the
    ## seats that would exceed it skip the call and take the `forester`
    ## directive with cause `rate_guard` — bounded, logged, never a sleep on the
    ## critical path (the raid round-2 sidecar-throttle scar).

proc initDecisionEngine*(sim: SimServer): DecisionEngine =
  result.client = newLlmClient(sim.config)
  for seat in 0 .. 1:
    result.seats[seat].baseline = blForester
    result.seats[seat].label = "lux-ai-forester"

proc policyKind*(engine: DecisionEngine, seat: int): string =
  if engine.seats[seat].isLlm: "llm" else: "scripted"

proc foresterFor*(engine: DecisionEngine, sim: SimServer, seat: int): Directive =
  ## The published `forester` directive. THE fallback, and the same proc the
  ## `forester` filler calls — `tests/test_lux_baselines.nim` asserts it.
  scriptedDirective(sim.world, blForester, seat)

# ---------------------------------------------------------------------------
#  Records
# ---------------------------------------------------------------------------

proc fallbackRecord*(turn, seat, attempt: int, cause, detail: string): string =
  $(%*{
    "k": "fallback",
    "turn": turn,
    "seat": seat,
    "attempt": attempt,
    "cause": cause,
    "detail": detail.truncateRunes(MaxFallbackDetailRunes)
  })

proc budgetGuardRecord*(turn, remainingSeconds: int): string =
  $(%*{"k": "budget_guard", "turn": turn, "remaining_s": remainingSeconds})

proc stopRecord*(turn: int): string =
  $(%*{"k": "stop", "turn": turn, "endRule": "wall_clock"})

# ---------------------------------------------------------------------------
#  How it went
# ---------------------------------------------------------------------------

proc snapshot(engine: var DecisionEngine, sim: SimServer, seat: int):
    tuple[since: array[3, int64], cities, workers, carts, lostTiles,
          lostUnits: int, story: string] =
  let world = sim.world
  for i in 0 .. 2:
    result.since[i] = world.resourcesMined[seat][i] - engine.lastSnapshot[seat][i]
    engine.lastSnapshot[seat][i] = world.resourcesMined[seat][i]
  let counts = [
    world.cityTilesBuilt[seat],
    world.units.countOf(Team(seat), ukWorker),
    world.units.countOf(Team(seat), ukCart),
    world.cityTilesLost[seat],
    world.unitsLost[seat]]
  result.cities = counts[0] - engine.lastCounts[seat][0]
  result.workers = max(0, counts[1] - engine.lastCounts[seat][1])
  result.carts = max(0, counts[2] - engine.lastCounts[seat][2])
  result.lostTiles = counts[3] - engine.lastCounts[seat][3]
  result.lostUnits = counts[4] - engine.lastCounts[seat][4]
  engine.lastCounts[seat] = counts
  ## Generated by the ENGINE, never by a model, and capped at 240 runes.
  var parts: seq[string] = @[]
  parts.add($world.units.countOf(Team(seat), ukWorker) & " workers mined " &
    $result.since[0] & " wood, " & $result.since[1] & " coal and " &
    $result.since[2] & " uranium")
  if result.cities > 0:
    parts.add($result.cities & " city tiles built")
  if result.lostTiles > 0:
    parts.add($result.lostTiles & " city tiles lost")
  if result.lostUnits > 0:
    parts.add($result.lostUnits & " units died in the open")
  result.story = parts.join("; ").truncateRunes(MaxHowItWentRunes)

# ---------------------------------------------------------------------------
#  The turn
# ---------------------------------------------------------------------------

proc rollingCount(engine: var DecisionEngine, now: MonoTime): int =
  var kept: seq[MonoTime] = @[]
  for at in engine.requestTimes:
    if (now - at).inSeconds < RollingWindowSeconds:
      kept.add(at)
  engine.requestTimes = kept
  kept.len

proc turn*(
  engine: var DecisionEngine,
  sim: var SimServer,
  elapsedSeconds: int
): seq[string] =
  ## Runs ONE directive turn and installs each seat's directive. Returns the
  ## replay chat records it produced. NEVER raises: every failure path ends in
  ## a legal directive, and no failure mode leaves a unit unactuated.
  let
    turnIndex = sim.world.turn
    budget = initDuration(milliseconds = max(1, sim.config.turnBudgetMs))
    turnStart = getMonoTime()
  ## Throttle state is PER TURN: a 429 on turn k says nothing about turn k+1.
  engine.client.throttled = false

  # --- budget guard: settle EARLY rather than overrun ----------------------
  if not engine.llmOff:
    let
      spacingSeconds = (sim.config.turnSpacingMs + 999) div 1000
      turnSeconds = (sim.config.turnBudgetMs + 999) div 1000
    if elapsedSeconds + 2 * (spacingSeconds + turnSeconds) >
        sim.config.wallClockBudgetSeconds:
      engine.llmOff = true
      result.add(budgetGuardRecord(turnIndex,
        max(0, sim.config.wallClockBudgetSeconds - elapsedSeconds)))
      echo "lux-ai: budget guard fired at turn ", turnIndex,
        "; remaining directive turns play scripted"

  # --- which seats need a call? --------------------------------------------
  var
    open: seq[int] = @[]
    views: array[2, JsonNode]
  let rolling = engine.rollingCount(getMonoTime())
  for seat in 0 .. 1:
    let story = engine.snapshot(sim, seat)
    views[seat] = sim.seatObservation(seat, story.since, story.cities,
      story.workers, story.carts, story.lostTiles, story.lostUnits, story.story)
    if not engine.seats[seat].isLlm:
      var directive = scriptedDirective(sim.world, engine.seats[seat].baseline, seat)
      directive.source = dsScripted
      sim.setDirective(seat, directive)
      continue
    let rateBlocked = rolling + 2 * (open.len + 1) > RollingRequestCap
    if (not engine.llmOff) and (not engine.client.disabled) and
        (not rateBlocked) and (not sim.seats[seat].dead):
      open.add(seat)
      continue
    ## An LLM seat that CANNOT call the LLM this turn is a FALLBACK, not a
    ## scripted policy — recording it is what makes `llmTurns` and
    ## `fallbackTurns` both countable.
    var directive = engine.foresterFor(sim, seat)
    directive.source = dsFallback
    sim.setDirective(seat, directive)
    inc sim.fallbackTurns[seat]
    let cause =
      if sim.seats[seat].dead: "disconnected"
      elif engine.llmOff: "budget_guard"
      elif rateBlocked: "rate_guard"
      else: "no_credentials"
    result.add(fallbackRecord(turnIndex, seat, 1, cause,
      "the LLM is unavailable for this turn; playing forester"))
    echo "lux-ai llm: seat ", seat, " falling back to forester (", cause,
      ") on turn ", turnIndex

  # --- the rate floor -------------------------------------------------------
  if open.len > 0 and engine.batchStarted and sim.config.turnSpacingMs > 0:
    let since = (getMonoTime() - engine.lastBatchStart).inMilliseconds.int
    if since < sim.config.turnSpacingMs:
      sleep(min(sim.config.turnSpacingMs, sim.config.turnSpacingMs - since))
  if open.len > 0:
    engine.lastBatchStart = getMonoTime()
    engine.batchStarted = true

  # --- up to two PARALLEL batches ------------------------------------------
  var attempt = 0
  while open.len > 0 and attempt < 2:
    if engine.client.disabled:
      break
    if getMonoTime() - turnStart >= budget:
      for seat in open:
        result.add(fallbackRecord(turnIndex, seat, attempt + 1, "timeout",
          "per-turn budget exhausted before attempt " & $(attempt + 1)))
      break
    let deadlineMs =
      if attempt == 0: sim.config.attempt1Ms else: sim.config.retryMs
    var batch: RequestBatch
    for seat in open:
      var user = $views[seat]
      if attempt > 0:
        user.add("\n\nYour previous reply was not usable. Reply with ONLY " &
          "the JSON object described above, starting with '{'.")
      let request = engine.client.requestFor(
        SystemPrompt, userMessage(engine.seats[seat].prompt, user))
      batch.post(request.url, request.headers, request.body, $seat)
      engine.requestTimes.add(getMonoTime())
    let started = getMonoTime()
    ## curly hands the deadline to CURLOPT_TIMEOUT, whose granularity is WHOLE
    ## SECONDS, so this conversion FLOORS — and `sim_config.validate` rejects a
    ## value that is not a whole number of seconds, so the floor is an identity.
    let responses = engine.client.curl.makeRequests(
      batch, max(1, deadlineMs div 1000))
    let latency = (getMonoTime() - started).inMilliseconds.int
    var stillOpen: seq[int] = @[]
    for position, seat in open:
      var cause = "parse_error"
      try:
        let text = engine.client.textOf(
          responses[position].response, responses[position].error,
          batch[position].url)
        var directive = parseDirective(
          extractJsonObject(text), sim.directive[seat], sim.config.mapSize)
        directive.source = dsLlm
        directive.latencyMs = latency
        sim.directivesRejected[seat] += directive.repaired
        sim.setDirective(seat, directive)
        inc sim.llmTurns[seat]
      except CatchableError as error:
        if responses[position].error.len > 0:
          cause = (if "timeout" in responses[position].error.toLowerAscii():
                     "timeout" else: "transport_error")
        elif error.msg.startsWith("llm throttled"):
          cause = "throttled"
        result.add(fallbackRecord(turnIndex, seat, attempt + 1, cause, error.msg))
        echo "lux-ai llm: seat ", seat, " attempt ", attempt + 1,
          " failed, falling back if it fails again: ", error.msg
        stillOpen.add(seat)
    open = stillOpen
    inc attempt
    if engine.client.throttled and open.len > 0:
      ## FAIL FAST: the only model left answered 429, so the retry batch would
      ## be refused the same way.
      echo "lux-ai llm: provider throttled with no other candidate; ",
        open.len, " seat(s) fall back for turn ", turnIndex
      break

  # --- anything still open plays forester for this turn --------------------
  for seat in open:
    var directive = engine.foresterFor(sim, seat)
    directive.source = dsFallback
    sim.setDirective(seat, directive)
    inc sim.fallbackTurns[seat]
    let cause =
      if engine.client.disabled or engine.client.transport == ltNone:
        "no_credentials"
      elif engine.llmOff: "budget_guard"
      elif engine.client.throttled: "throttled"
      else: "parse_error"
    result.add(fallbackRecord(turnIndex, seat, 2, cause,
      "seat fell back to the forester directive"))
    ## "falling back" is the phrase phase 60 greps the GAME log for.
    echo "lux-ai llm: seat ", seat, " falling back to forester (", cause,
      ") on turn ", turnIndex

  # --- the presentation records --------------------------------------------
  for seat in 0 .. 1:
    result.add($sim.directive[seat].directiveRecord(
      turnIndex, seat, cogAlias(seat), views[seat]))
    sim.world.emitEvent(sim.tickCount, SimEvent(
      kind: Directive, seat: seat, content: $sim.directive[seat].stance,
      cause: sim.directive[seat].note))
